### ISSUE TITLE
Error when using XeLaTeX, but working (with limitations) in LuaLaTeX

### ISSUE THREAD

**Issue by RGB-es** [georgd/EB-Garamond-Initials#4]
I'm testing the new initial fonts on LyX, but when I set the engine to use XeTeX, I get a "Missing glyph!" error with "Missing character: There is no   (U+0020) in font EB Garamond Initials!" as description. If I switch to LuaTeX as engine, the document compile without problems, but the initial is too big and cover the next line. For example, if I set `\setcounter{DefaultLines}{3}` the character goes into the fourth line, covering the text.

![test-initials-luatex](https://user-images.githubusercontent.com/7756783/231185783-bc109db2-0d6f-4501-9d28-a3ca02dd4ff2.png)

The preamble is quite simple: I activate the lettrine package (through a module on LyX) and then

```
\newfontfamily{\Iniciales}{EB Garamond Initials}
\renewcommand{\LettrineFontHook}{\Iniciales}
\setcounter{DefaultLines}{3}

```

**Comment by georgd** [comment]
Thanks for reporting this issue. I can't tell for sure but I have a suspicion what's happening: The vertical metrics have never been set correctly. The source files haven't been changed in this regard between the old incarnation and the recent one.

 But Fontforge seemingly changed: although the parameter `OS2_UseTypoMetrics` was set in the SFD files, it wasn't set in the generated fonts. Some time in the past nine years this was fixed. Thus, now vertical placement is out of order. This also affects the EBG text fonts, as reported by another user. Luckily, there it isn't that bad because the settings are much better.

**Comment by georgd** [comment]
I’m a bit lost there. My assumption was wrong. What I observed was confined to the text font. I can replicate your experience but even worse, I can’t replicate the desired behavior even with v0.016. We probably need som LaTeX guru’s help?

**Comment by amarz45** [comment]
I’m pretty sure what causes is is the fact that the `lettrine` package resizes the height of the letter but the depth is not eliminated. Try inserting a letter with EB Garamond Initials at the regular body size, you will notice that it descends—just like the lowercase P, for example.

![import-2023-04-11_21:42:00](https://user-images.githubusercontent.com/92645199/231325422-ca97c3dd-119d-4cc3-a6fc-ba0e0f37a5b7.png)

When it is scaled up, it still descends which is not what we want. The best way to get around this is to simply rescale it and move it up, and the `lettrine` package already provides a way to do that. Just add the following lines to your preamble.

```tex
% https://github.com/timgrei/coloredlettrine/blob/master/lettrine.cfg
\renewcommand{\DefaultLoversize}{-0.249461935032}
\renewcommand{\DefaultLraise}{0.266022007336}
```

The values shown above are taken from [timgrei](https://github.com/timgrei)’s [coloredlettrine](https://github.com/timgrei/coloredlettrine) repository. I don’t know how he calculated them to such a precision, but they seem perfect to me.

```tex
\documentclass{article}

\usepackage{fontspec, lettrine}

\setmainfont{EB Garamond}

\newfontfamily{\Iniciales}{EB Garamond Initials}
\renewcommand{\LettrineFontHook}{\Iniciales}
\setcounter{DefaultLines}{3}

% https://github.com/timgrei/coloredlettrine/blob/master/lettrine.cfg
\renewcommand{\DefaultLoversize}{-0.249461935032}
\renewcommand{\DefaultLraise}{0.266022007336}

\begin{document}

\lettrine{L}{orem} ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
sunt in culpa qui officia deserunt mollit anim id est laborum.

\end{document}
```

![import-2023-04-11_21:41:20](https://user-images.githubusercontent.com/92645199/231325325-83fef411-f89a-44fb-99c3-04d0f920e056.png)

I got the same result compiling with XeLaTeX and LuaLaTeX, although I prefer LuaLaTeX because of support for certain packages and more microtype features. I think the fact that it is not working on XeLaTeX for you might be caused by LyX doing something under the hood. Can you try compiling the document shown above?

P.S. There is also a question on TeX StackExchange about this: https://tex.stackexchange.com/questions/428807/lettrine-with-eb-garamond-initials.

**Comment by amarz45** [comment]
It might be suitable to fix this on the font level so that we do not have to work around it on the typesetting system level.

**Comment by georgd** [comment]
Hmm. So, eliminating the descender height might possibly fix this. I know I did some experiments back when I started working on this font and for some reason I came to the conclusion that I needed the descender. But I can't recall what it was.

**Comment by RGB-es** [comment]
Just installed the latest version and it seems that the problem with XeTeX is fixed: the document compile without error now. The other problem is still present, so for now I'm adding a `\renewcommand{\DefaultLraise}{0.26}` line to the preamble to avoid the collision by rising the character.

**Comment by RGB-es** [comment]
Noticed the last-latest version, installed it and now everything works. Perfect! Many thanks for your work!
